### ISSUE TITLE
numpy.ndarray size changed?

### ISSUE THREAD

**Issue by tlupien-personal** [joshlk/k-means-constrained#18]
![error](https://user-images.githubusercontent.com/34693805/150421781-42094474-74d9-45ac-b9ce-24e2d1a972eb.png)

I am getting the above error when I attempt to use this. This is what it said when I installed the latest version as was the recommended solution to a similar issue:

![install](https://user-images.githubusercontent.com/34693805/150422309-189298f1-07b8-4e39-916b-ee45eea70c05.png)

I use Ubuntu 20.04.03, Python 3.8.10, and am in working in Jupyter Lab 3.2.4.

This is a similar issue I found for another package (which I don't currently use) while researching this problem, if that is helpful: https://github.com/MaartenGr/BERTopic/issues/392

It seems notable to me that now it's asking for 96 and getting 88, when before (in https://github.com/joshlk/k-means-constrained/issues/12) it was asking for 88 and getting 80, but I am unfamiliar with this topic area.

Apologies if this is just me doing something wrong.

**Comment by Warren-S5** [comment]
I am experiencing the same issue as above, with the error message returned being:
` numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

**Comment by joshlk** [comment]
Hi all, thanks for using k-means-constrained 🚀!

Sorry for the long wait. I have updated the package on PyPI - can you please try the new version `pip install --upgrade k-means-constrained` should do the trick (make sure it installs the v0.7.0 version). What I did was bump numpy up as I think its due to binary incompatibility between versions.

If the problem still persists can you please make sure the numpy version installed is `1.21.5` and let me know if that solves the issue.

**Comment by danvip10** [comment]
Hi @joshlk, unfortunately I just upgraded to to `k-means-constrained v0.7.0` and I still get exactly the same error... I do have `numpy 1.25.5` .
As posted by @Warren-S5 the errror is `ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

**Comment by joshlk** [comment]
Can you please downgrade numpy to `1.21.5` to see if it resolves the issue. I would recommend doing this in a virtual environment

**Comment by joshlk** [comment]
By the way numpy `1.25.5` currently does not exist 🤔  (see [PyPI](https://pypi.org/project/numpy/#history)). The current latest version is `1.22.3`. Can you paste me the result of `python -c "import numpy; print(numpy.__version__)"`

**Comment by danvip10** [comment]
sorry that was a typo, I mean `numpy 1.21.5`

**Comment by joshlk** [comment]
Ok can you please provide me with the following version:

- Python: 
- Operating system: [Windows/MacOS/Linux]
- k-means-constrained: 
- numpy:
- cython (if installed):

**Comment by danvip10** [comment]
`Python 3.8.10 
Operating system: Ubuntu 20.04.3 LTS (Focal Fossa)
numba                             0.55.0              
numpy                             1.21.5 
Cython                            0.29.28             
`

**Comment by joshlk** [comment]
I've just tested on Ubuntu 20.04.3 with the above versions and it works fine for me. Did you change the numpy version after installing `k-means-constrained`? Could you try uninstalling `numpy` and `k-means-constrained`, and then install `numpy==1.21.5` and then `k-means-constrained`

**Comment by danvip10** [comment]
I just uninstalled and re-installed `numpy==1.21.5` and `k-means-constrained` (`0.7.0`)`but it didn't change anything. 
When running  `from .k_means_constrained_ import KMeansConstrained` on a python instance I still get the same error specified above

**Comment by danvip10** [comment]
If it helps the error is also raised by doing just `import k_means_constrained`. See the full error message below
```
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import k_means_constrained
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daniel/.local/lib/python3.8/site-packages/k_means_constrained/__init__.py", line 4, in <module>
    from .k_means_constrained_ import KMeansConstrained
  File "/home/daniel/.local/lib/python3.8/site-packages/k_means_constrained/k_means_constrained_.py", line 18, in <module>
    from .sklearn_import.metrics.pairwise import euclidean_distances
  File "/home/daniel/.local/lib/python3.8/site-packages/k_means_constrained/sklearn_import/metrics/pairwise.py", line 10, in <module>
    from k_means_constrained.sklearn_import.metrics.pairwise_fast import _sparse_manhattan
  File "k_means_constrained/sklearn_import/metrics/pairwise_fast.pyx", line 1, in init k_means_constrained.sklearn_import.metrics.pairwise_fast
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

```

**Comment by joshlk** [comment]
@danvip10 I've updated the `k-means-constrained` version. Can you please create a new virtual environment. Something like:
```
python3 -m venv ~/venv_test
source ~/venv_test/bin/activate
```

And then install the new version

**Comment by danvip10** [comment]
It worked! Thanks. 

As a note, it's worth mentioning that the `pip install k-means-constrained` installed `numpy-1.22.3`, which for the moment is incompatible with my `numba 0.55.1` installation (which has requirement `numpy < 1.22`). 

As long as `numpy>=1.22.0`, then `k-means-constrained` works, but other packages might not have updated their `numpy` dependencies.  

Thanks for fixing it @joshlk

**Comment by joshlk** [comment]
Great. Closing this ticket. Others - please reopen if problem persists
